Company_List/Models/TransactionType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Company_List.Models
{
    /// <summary>
    /// Properties of Transactiontype
    /// </summary>
    public class TransactionType
    {
        
        public string TransactionTypeId { get; set; }
        
        public string TransactionName { get; set; }

        public double? CommissionFee { get; set; }




    }
}

Company_List/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Company_List.Models;

namespace EmployeesApplication_Week5.Controllers
{
    public class CompanyController : Controller
    {
        private readonly TransactionContext _context;

        // Prepare controller for database context communication
        public CompanyController(TransactionContext context)
        {
            _context = context;
        }

        // GET: Company/Index
        public IActionResult Index()
        {
            return View(_context.Company.ToList());
        }
        
        // get company details using id 
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = _context.Company.FirstOrDefault(m => m.CompanyID == id);
            
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        // GET: Company/Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        // Create the data for Company 
        [HttpPost]
        public IActionResult Create(Company company)
        {
            if (ModelState.IsValid)
            {
                _context.Add(company);
                _context.SaveChanges();

                //Temp data is used in header for infomation is added.
                TempData["action"] = company.CompanyName + " has been added.";
                TempData["isSuccessful"] = "Success";

                return RedirectToAction(nameof(Index));
            }
            
           
            TempData["action"] = company.CompanyName + " was not added.";
            TempData["isSuccessful"] = "Failed";

            return View(company);
        }

        // GET: Company/Edit
        //Edit method is done by id which allows to do edit on click event of Edit
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // Find the value of Edit using Id
            var company = _context.Company.Find(id);

            if (company == null)
            {
                return NotFound();
            }
            return View(company);
        }

        //If modelstate is valid then it allow to do Update
        [HttpPost]
        public IActionResult Edit(Company company)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(company);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompanyExists(company.CompanyID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

               //Called Event is it Succesful or Not
                TempData["action"] = company.CompanyName + " was updated.";
                TempData["isSuccessful"] = "Success";

                return RedirectToAction(nameof(Index));
            }

            
            TempData["action"] = company.CompanyName + " was not updated.";
            TempData["isSuccessful"] = "Failed";

            return View(company);
        }

        // GET: Company/Delete
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

          //Attemo to match the data using Company id
            var company = _context.Company.FirstOrDefault(m => m.CompanyID == id);

            if (company == null)
            {
                return NotFound();
            }
            
            return View(company);
        }


        //Remove data from the database 
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(Company company)
        {
           
            TempData["action"] = company.CompanyName + " was deleted.";
            TempData["isSuccessful"] = "Success";

            _context.Company.Remove(company);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        // Local method to assist with the process of identifying if the company entry exists in the 
        // database based on whether or not the provided CompanyID matches a record in the Company
        // table.
        private bool CompanyExists(int id)
        {
            return _context.Company.Any(e => e.CompanyID == id);
        }
    }
}

Company_List/Controllers/TransactionController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Company_List.Models;

namespace EmployeesApplication_Week5.Controllers
{
    public class TransactionController : Controller
    {
        private readonly TransactionContext _context;

        //Controller for database context
        public TransactionController(TransactionContext context)
        {
            _context = context;
        }


        // GET: Transaction/Index/sortOrder
        //Sort the data of transaction in the Ascending and Desending Style Format
        public IActionResult Index(string sortOrder)
        {
           ///Set the cookies data of user
            CookieOptions cookieOptions = new CookieOptions { Expires = DateTime.Now.AddSeconds(20) };
            HttpContext.Response.Cookies.Append("newUser", "Divyesh", cookieOptions);

         
            ViewBag.SortOrder = sortOrder == "SortByAsc" || sortOrder == null ? 
                "SortByDesc" : "SortByAsc";

            var transactions = _context.Transactions
                .Include(i => i.TransactionType)
                .Include(i => i.Company)
                .ToList();

           //switch order the data 
            switch (sortOrder)
            {
                case "SortByAsc":
                    transactions = transactions.OrderBy(ob => ob.Company.CompanyName).ToList();
                    break;

                case "SortByDesc":
                    transactions = transactions.OrderByDescending(obd => obd.Company.CompanyName).ToList();
                    break;

                default:
                    transactions = transactions.OrderBy(ob => ob.Company.CompanyName).ToList();
                    break;
            }

           
            return View(transactions);
        }


        // GET: Transaction/TransactionList
        //Diplay all the transactions which is added by the user
        //for that called the compnay and transaction database set in to variablr
        public IActionResult TransactionList(int id)
        {
            Company company = _context.Company.Where(w => w.CompanyID == id).FirstOrDefault();

            ViewBag.CompanyName = company.CompanyName;
            ViewBag.TickerSymbol = company.TickerSymbol;

            var transactionsList = _context.Transactions
                .Include(i => i.TransactionType)
                .Include(i => i.Company)
                .Where(w => w.CompanyID == id)
                .ToList();

            return View(transactionsList);
        }


        // GET: Transaction/Details  
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

          
            var transaction = _context.Transactions.FirstOrDefault(m => m.TransactionId == id);

            if (transaction == null)
            {
                return NotFound();
            }

            return View(transaction);
        }

        // Return to the Create Method 
        public IActionResult Create()
        {
            ViewBag.TransactionType = _context.TransactionTypes.ToList();
            ViewBag.Company = _context.Company.ToList();
            return View();
        }

       //Trabnsaction/Create
       //Add new data into  the transction database
        [HttpPost]
        public IActionResult Create(Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                _context.Add(transaction);
                _context.SaveChanges();
                var company = _context.Company.Find(transaction.CompanyID);

                TempData["action"] = company.CompanyName + " " +    " Data was added to the Transaction database.";
                TempData["isSuccessful"] = "Success";

                return RedirectToAction("Index");
            }

           //Tempdata which saws the data has store Successfully
            TempData["action"] = transaction.Company.CompanyName + " " + " was NOT added to the Transaction database.";
            TempData["isSuccessful"] = "Failed";

            return View(transaction);
        }

      
      /// <summary>
      /// 
      /// </summary>
      /// <param name="id"></param>
      /// <returns></returns>
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ViewBag.TransactionType = _context.TransactionTypes.ToList();
            ViewBag.Company = _context.Company.ToList();

        
            var transaction = _context.Transactions.Find(id);

            if (transaction == null)
            {
                return NotFound();
            }
            return View(transaction);
        }

      
        [HttpPost]
        // GET: Transaction/Edit
        //Edit method is done by id which allows to do edit on click event of Edit
        //Id find the value which will be depends on the modelstate if its true then its will do updte
        public IActionResult Edit(Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(transaction);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TransactionExists(transaction.TransactionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

              //Tempdata which saws the result or transaction process is done
                TempData["action"] = transaction.Company.CompanyName + " " + transaction.Company.TickerSymbol + " was updated.";
                TempData["isSuccessful"] = "Success";

                return RedirectToAction(nameof(Index));
            }
            
            TempData["action"] = transaction.Company.CompanyName + " " + transaction.Company.TickerSymbol + " was NOT updated.";
            TempData["isSuccessful"] = "Failed";

            return View(transaction);
        }

       /// <summary>
       /// Find the result using Id and allow it to delete the data
       /// </summary>
       /// <param name="id"></param>
       /// <returns></returns>
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

          
            var transaction = _context.Transactions.FirstOrDefault(m => m.TransactionId == id);
            ViewBag.Company = _context.Company.ToList();

            if (transaction == null)
            {
                return NotFound();
            }

            return View(transaction);
        }

        /// <summary>
        /// deleteConfird method is used to delete the data by find thr the particular Id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        //Remove the data from the database and update the data
        [HttpPost]
        public IActionResult DeleteConfirmed(int id)
        {
            var transaction = _context.Transactions.Find(id);
            var company = _context.Company.Find(transaction.CompanyID);

            _context.Transactions.Remove(transaction);
            _context.SaveChanges();

            TempData["action"] = company.CompanyName + " " + "  was deleted into the database.";
            TempData["isSuccessful"] = "Success";

            return RedirectToAction(nameof(Index));
        }

        
        private bool TransactionExists(int id)
        {
            return _context.Transactions.Any(e => e.TransactionId == id);
        }
    }
}

Company_List/Views/Transaction/Create.cshtml
@model Company_List.Models.Transaction


@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
     

            <div class="form-group">
                <label asp-for="CompanyID">Company</label>
                <select class="form-control" asp-for="CompanyID" asp-items="@(new SelectList(ViewBag.Company, "CompanyID", "CompanyName"))">
                </select>
            </div>

            <!-- Retrieve list  from the database which are inserted into a ViewBag property called "TransactionTypes" -->
            <div class="form-group">
                <label asp-for="TransactionTypeId">TransactionType</label>
                <select class="form-control" asp-for="TransactionTypeId" asp-items="@(new SelectList(ViewBag.TransactionType, "TransactionTypeId", "TransactionName"))">
                </select>
            </div>

            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SharePrice" class="control-label"></label>
                <input asp-for="SharePrice" class="form-control" />
                <span asp-validation-for="SharePrice" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Company_List/Views/Transaction/Delete.cshtml
@model Transaction
@{
    ViewBag.Title = "Delete Transaction";
}

@*Delete File for delete the data of transactionlist*@



<h2>Confirm Deletion: </h2>


    <h3>@Model.Quantity shares @Model.Company.CompanyName of share price: @Model.SharePrice</h3>




<form asp-action="DeleteConfirmed" asp-route-id="@Model.TransactionId">
    @*<input type="hidden" asp-for="TransactionId" />*@

    <button type="submit" class="btn btn-primary">Delete</button>
    <a asp-controller="Transaction" asp-action="Index" class="btn btn-primary">Cancel</a>
</form>

Company_List/Views/Transaction/Details.cshtml
@model Company_List.Models.Transaction

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Transaction</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Company.CompanyName)
        </dt>
        <dd class="col-sm-10">
         
        </dd>
        
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TransactionType.TransactionName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SharePrice)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.TransactionId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Company_List/Views/Transaction/Edit.cshtml
@model Company_List.Models.Transaction


@{
    ViewData["Title"] = "Edit";
}

<h1>Create</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TransactionId" />

            <div class="form-group">
                <label asp-for="CompanyID">Company</label>
                <select class="form-control" asp-for="CompanyID" asp-items="@(new SelectList(ViewBag.Company, "CompanyID", "CompanyName"))">
                </select>
            </div>

            <!-- Retrieve list  from the database which are inserted into a ViewBag property called "TransactionTypes" -->
            <div class="form-group">
                <label asp-for="TransactionTypeId">TransactionType</label>
                <select class="form-control" asp-for="TransactionTypeId" asp-items="@(new SelectList(ViewBag.TransactionType, "TransactionTypeId", "TransactionName"))">
                </select>
            </div>

            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SharePrice" class="control-label"></label>
                <input asp-for="SharePrice" class="form-control" />
                <span asp-validation-for="SharePrice" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Company_List/Views/Transaction/Index.cshtml
@model IEnumerable<Company_List.Models.Transaction>

@{
    ViewData["Title"] = "Index";
}

<h1>Transactions</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Company.TickerSymbol)
            </th>
            <th>
                <a asp-controller="Company" asp-action="Index" asp-route-sortOrder="@(ViewBag.SortOrder)">
                    @Html.DisplayNameFor(model => model.Company.CompanyName)
                </a>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SharePrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TransactionType.TransactionName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TransactionType.CommissionFee)
            </th>
            <th>
                Gross Value
            </th>
            <th>
                Net Value
            </th>
           
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Company.TickerSymbol)
            </td>
            <td>
                
                    @Html.DisplayFor(modelItem => item.Company.CompanyName)
                
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SharePrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TransactionType.TransactionName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TransactionType.CommissionFee)
            </td>
            @if (item.TransactionType.TransactionName == "Buy")
            {
                <td>$(@item.GetGrossValue()?.ToString("0.00"))</td>
                <td>$(@item.GetNetValue()?.ToString("0.00"))</td>
            }
            else
            {
                <td>@item.GetGrossValue()?.ToString("c2")</td>
                <td>@item.GetNetValue()?.ToString("c2")</td>
            }


           
        </tr>
}
    </tbody>
</table>

Company_List/Views/Transaction/TransactionList.cshtml
@model IEnumerable<Company_List.Models.Transaction>

@{
    ViewData["Title"] = "Index";
}

<h2>@ViewBag.CompanyName</h2>
<h2>@ViewBag.TickerSymbol</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SharePrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Company.CompanyName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TransactionType)
            </th>
            <th>
              
            </th>
            
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
            
                    @Html.DisplayFor(modelItem => item.Quantity)
                
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SharePrice)
            </td>
            <td>
                <a asp-controller="Company" asp-action="Edit" asp-route-id="@(item.CompanyID)">
                    @Html.DisplayFor(modelItem => item.Company.CompanyName)
                </a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TransactionType.TransactionName)
            </td>
            
            <td>
                <a asp-action="Edit" asp-route-id="@item.TransactionId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.TransactionId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.TransactionId">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>